#配置数据源信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zg_test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    #com.mysql.jdbc.Driver是MySQL 5版本的。MySQL 5以上需要使用 com.mysql.cj.jdbc.Driver

mybatis:
  # 配置mybatis的resultType别名，默认是别名为小写
  type-aliases-package: com.lexiaoyao.mybatisdemo.domain
  # 配置扫描的xml文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml
  # mybatis详细配置文件
  config-location: classpath:mybatis/mybatis-config.xml
  # 扫描handler组件
  type-handlers-package: com.lexiaoyao.mybatisdemo.handler
logging:
  config: classpath:logconfig/logback.xml
